---

R1:
    hostname: "192.168.31.101"
    groups:
        - cisco_group
        - north

R2:
    hostname: "192.168.31.102"
    groups:
        - cisco_group
        - north

R3:
    hostname: "192.168.31.103"
    groups:
        - cisco_group
        - north

R4:
    hostname: "192.168.31.104"
    groups:
        - cisco_group
        - north
