---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: "groups.yaml"
        defaults_file: "defaults.yaml"

runners:
    plugin: threaded
    options:
        num_workers: 10
