---

Spine1:
    username: "admin"
    password: "admin"
    hostname: 10.188.188.101
    groups:
        - cisco_group


 
Spine2:
    username: "admin"
    password: "admin"
    hostname:  10.188.188.102
    groups:
        - cisco_group

Leaf3:
    username: "admin"
    password: "admin"
    hostname: 10.188.188.103
    groups:
        - cisco_group


Leaf4:
    username: "admin"
    password: "admin"
    hostname: 10.188.188.104
    groups:
        - cisco_group


Leaf5:
    username: "admin"
    password: "admin"
    hostname: 10.188.188.105
    groups:
        - cisco_group


Leaf6:
    username: "admin"
    password: "admin"
    hostname: 10.188.188.106
    groups:
        - cisco_group
