---

snmp:
    snmp_community: "IPvZero2"

ospf:
    ospf_rid: 8.8.8.8

bgp:
   asn: "65001"
   rid: 8.8.8.8
   update_source: "loopback0"
   route_reflector: False
   neighbors:
       - 2.2.2.2
       - 3.3.3.3
