---

inventory:
    plugin: SimpleInventory
    options:
            #CHANGE THESE PATHS TO MATCH YOUR OWN
        host_file: "/home/ipvzero/Nornir3/hosts.yaml"
        group_file: "/home/ipvzero/Nornir3/groups.yaml"
        defaults_file: "/home/ipvzero/Nornir3/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 10
