---

Spine1:
  hostname: "192.168.31.101"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Spine2:
  hostname: "192.168.31.102"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Leaf3:
  hostname: "192.168.31.103"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Leaf4:
  hostname: "192.168.31.104"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Leaf5:
  hostname: "192.168.31.105"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Leaf6:
  hostname: "192.168.31.106"
  username: "john"
  password: "cisco"
  port: 22
  groups:
    - cisco_group

Leaf7:
  hostname: "192.168.31.107"
  username: "john"
  password: "arista"
  port: 22
  groups:
    - arista_group

Leaf8:
  hostname: "192.168.31.108"
  username: "john"
  password: "arista"
  port: 22
  groups:
    - arista_group
