---

Hub:
    hostname: 192.168.31.101
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: yes


Spoke1:
    hostname: 192.168.31.102
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: yes



Spoke2:
    hostname: 192.168.31.103
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: yes



Spoke3:
    hostname: 192.168.31.104
    groups:
        - cisco_group
    data:
        domain: ipvzero
        dmvpn: yes
