---
vrfs:
  - name: GREEN 
    rd: "25:3"
    targets:
      - direction: export
        target_tag: "25:3"
      - direction: import
        target_tag: "25:3"

  - name: RED 
    rd: "25:2"
    targets:
      - direction: export
        target_tag: "25:2"
      - direction: import
        target_tag: "25:2"

  - name: MGMT
  
BGP:
    ASN: "25"
    neighbors:
      - 2.2.2.2
      - 3.3.3.3
      - 4.4.4.4
    vrfs:
      - name: GREEN
        redistribute_process: 3
        ospf_rid: 172.1.3.3
      - name: RED
        redistribute_process: 2
        ospf_rid: 172.1.2.2

OSPF:
    process: 1
    ospf_rid: 172.1.1.1
