---
- name: Testing Scrapli in Ansible
  hosts: all
  tasks:
    - name: Using the new Scrapli OSPF module
      ospf_table:
        ip: "{{ ansible_host }}"
      register: result

    - name: Printing the output
      debug:
        msg: "{{ result.data.result.split('\n') }}"

