---

- name: "Using NAPALM within Ansible"
  hosts: all

  tasks:
    - name: "Pull info from devices using NAPALM"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["facts"]
      register: result
    
    - name: "Printing the Result"
      debug:
        msg: "{{ result.ansible_facts.napalm_facts.hostname }}"