---

- name: "OSPF Configs via Jinja"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Configure VyOS OSPF"
      vyos.vyos.vyos_config:
        src: "{{ ansible_network_os }}-ospf.j2"
      register: vyos_output
      when: "ansible_network_os == 'vyos.vyos.vyos'"

    - name: "Print VyOS config"
      debug:
        msg: "{{ vyos_output }}"
      when: "ansible_network_os == 'vyos.vyos.vyos'"

    - name: "Configure Cisco OSPF"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-ospf.j2"
      register: cisco_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Print Cisco config"
      debug:
        msg: "{{ cisco_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"