---

- name: "Playbook to test NAPALM-Ansible"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Retrieve device facts from via NAPALM"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["vlans"]

      register: result

    - name: "Print Result"
      debug:
        msg: "{{ result.ansible_facts.napalm_vlans }}"